# .scrutinizer.yml
build:

    nodes:
        '7.1':
            environment:
                php: '7.1'
        '7.2':
            environment:
                php: '7.2'
        '7.3':
            environment:
                php: '7.3'

    environment:
        php:
            ini:
                'xdebug.mode': "coverage"

    dependencies:
        override:
            - COMPOSER_MEMORY_LIMIT=-1 composer update

    project_setup:
        before:
            - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar -O coveralls.phar
            - chmod +x coveralls.phar
            - php coveralls.phar --version

    tests:
        before:
            - mkdir -p build/logs
        override:
            -   command: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                coverage:
                    file:   build/logs/clover.xml
                    format: clover
        after:
            - php coveralls.phar -v

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - "tests/*"
        - "vendor/*"

tools:
    php_analyzer:      true
    php_code_sniffer:  true
    php_cpd:           true
    php_cs_fixer:      true
    php_loc:           true
    php_mess_detector: true
    php_pdepend:       true
