# .scrutinizer.yml
builds:
    nodes:
        'php_7.1':
            environment:
                php: '7.1'
        'php_7.2':
            environment:
                php: '7.2'

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - "tests/*"
        - "vendor/*"

tools:
    php_analyzer:      true
    php_code_sniffer:  true
    php_cpd:           true
    php_cs_fixer:      true
    php_loc:           true
    php_mess_detector: true
    php_pdepend:       true
