# .scrutinizer.yml
build:

    nodes:
        'PHP: 7.1':
            environment:
                php: 7.1.33
        'PHP: 7.2':
            environment:
                php: 7.2.34
        'PHP: 7.3':
            environment:
                php: 7.3.26
        'PHP: 7.4':
            environment:
                php: 7.4.14
        'PHP: 8.0':
            environment:
                php: 8.0.1

    environment:
        php:
            ini:
                'xdebug.mode': "coverage"

    dependencies:
        before:
            - if [ "" == "$(php -m | grep zip)" ]; then pecl install zip; fi;
        override:
            - COMPOSER_MEMORY_LIMIT=-1 composer update

    project_setup:
        before:
            - wget -c -nc --retry-connrefused --tries=0 https://scrutinizer-ci.com/ocular.phar -O ocular.phar
            - chmod +x ocular.phar
            - php ocular.phar --version

    tests:
        before:
            - mkdir -p build/logs
        override:
            -   command: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                coverage:
                    file:   build/logs/clover.xml
                    format: clover

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - "tests/*"
        - "vendor/*"

tools:
    php_analyzer:      true
    php_code_sniffer:  true
    php_cpd:           true
    php_cs_fixer:      true
    php_loc:           true
    php_mess_detector: true
    php_pdepend:       true
