# .github/workflows/travis.yml
name: "build"

on: [ push, release, pull_request ]

jobs:
    build:
        name:    "PHP ${{ matrix.php-version }}"
        runs-on: ubuntu-18.04

        strategy:
            matrix:
                php-version:
                    - "7.1"
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions:  "zip"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "Tests"
                run:  |
                      mkdir -p build/logs
                      vendor/bin/phpunit --coverage-clover build/logs/clover.xml

            -   name: ""
                uses: coverallsapp/github-action@v1.1.2
                    with:
                        github-token: ${{ secrets.github_token }}
                        flag-name:    PHP-${{ matrix.php-version }}
                        parallel:     true

    coverage:
        name:    "Coverage"
        runs-on: ubuntu-18.04
        needs:   "build"

        steps:
            -   name: ""
                uses: coverallsapp/github-action@v1.1.2
                with:
                    github-token:      ${{ secrets.github_token }}
                    parallel-finished: true
