# .github/workflows/travis.yml
name: "build"

on: [ push, release, pull_request ]

jobs:

    build:
        name:    "PHP ${{ matrix.php-version }}"
        runs-on: ubuntu-18.04

        strategy:
            matrix:
                php-version:
                    - "7.1"
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions:  "zip"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "Application"
                run:  |
                      mkdir -p build/logs
                      wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar -O coveralls.phar
                      chmod +x coveralls.phar
                      php coveralls.phar --version

            -   name: "Tests"
                run:  vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-html build/logs

            -   name: "Coverage"
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    COVERALLS_FLAG_NAME:  php-${{ matrix.php-version }}
                    COVERALLS_PARALLEL:   true
                run:  php coveralls.phar -v

            -   name: "Compress artifact"
                run:  zip -r build/logs.zip build/logs -x build/logs/clover.xml

            -   name: "Upload artifact"
                uses: actions/upload-artifact@v2
                with:
                    name: "coverage-${{ matrix.php-version }}.zip"
                    path: build/logs.zip

    coverage:
        name:    "Coverage"
        runs-on: ubuntu-18.04
        needs:   "build"

        steps:
            -   name: "Coverage"
                uses: coverallsapp/github-action@v1.1.2
                with:
                    github-token:      ${{ secrets.github_token }}
                    parallel-finished: true

    metrics:
        name:    "Metrics"
        runs-on: ubuntu-18.04
        needs:   "build"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "7.1"
                    extensions:  "zip"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "Application"
                run:  |
                      mkdir -p build/logs
                      wget -c -nc --retry-connrefused --tries=0 https://github.com/phpmetrics/PhpMetrics/releases/download/v2.7.3/phpmetrics.phar -O phpmetrics.phar
                      chmod +x phpmetrics.phar
                      php phpmetrics.phar --version

            -   name: "Tests"
                run:  vendor/bin/phpunit --log-junit build/logs/junit.xml

            -   name: "Metrics"
                run:  php phpmetrics.phar --report-html=build/logs/ src/ --git --junit=build/logs/junit.xml

            -   name: "Compress artifact"
                run:  zip -r build/logs.zip build/logs -x build/logs/junit.xml

            -   name: "Upload artifact"
                uses: actions/upload-artifact@v2
                with:
                    name: "metrics.zip"
                    path: build/logs.zip
