# .github/workflows/travis.yml
name: "Travis CI"

on:
    push:
    pull_request:

jobs:
    build:

        runs-on: "ubuntu-18.04"

        strategy:
            matrix:
                php-version:
                    - "7.1"
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Build environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions:  "zip"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  |
                      COMPOSER_MEMORY_LIMIT=-1 composer update
                      wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar -O coveralls.phar
                      chmod +x coveralls.phar
                      php coveralls.phar --version

            -   name: "Tests"
                run:  |
                      mkdir -p build/logs
                      vendor/bin/phpunit --coverage-clover build/logs/clover.xml
